export const REFERENCE_CATEGORIES = [
  "Landscape",
  "Seascape",
  "Rivers and Lakes",
  "Mountains",
  "Forest and Trees",
  "Skies and Clouds",
  "Sunrise and Sunset",
  "Flowers and Florals",
  "Still Life",
  "Architecture",
  "Street Scene",
  "People and Portraits",
  "Animals and Birds",
  "Boats and Harbors",
  "Countryside",
  "Urban Sketching",
  "Textures and Details",
  "Seasonal",
] as const;

export const REFERENCE_COUNTRIES = [
  "Sri Lanka",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "India",
  "China",
  "Japan",
  "South Korea",
  "France",
  "Germany",
  "Italy",
  "Spain",
  "Netherlands",
  "Turkey",
  "Russia",
  "Thailand",
  "Indonesia",
  "Malaysia",
  "Singapore",
  "New Zealand",
  "South Africa",
  "Brazil",
  "Mexico",
  "Other",
] as const;
